version: '3.4'

services:
  webapi:
    container_name: webapi
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      - ConnectionStrings__BeerQuestDatabaseConnectionString=Data Source=sql-server-database; Initial Catalog=BeerQuest; User Id=sa; Password=LocalUserPassword1*
    depends_on:
      - sql-server-database
    restart: always
    tty: true
    ports:
      - "8001:443"
      - "8000:80"

  sql-server-database:
    container_name: sql-server-database
    image: mcr.microsoft.com/mssql/server
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: always
    environment:
      SA_PASSWORD: LocalUserPassword1*
      ACCEPT_EULA: "Y"
    tty: true
    ports:
      - "1433:1433"

volumes:
  sqlserver-data: